### PR TITLE
operator: Make str+null concat "null"

### PR DESCRIPTION
**Pull request by johannes-wolf**
Implementation of #78. I am not sure if maybe adding `""` would be better?

### CODE REVIEW

**Comment by fklebert** [comment]
> Implementation of #78. I am not sure if maybe adding `""` would be better?

I am not the expert in SIMFIL, but as long as `null` is a real SIMFIL value (comparable to SQL's "NULL"), then for me "empty string" is a different thing than `null`.

**Review by fklebert — APPROVED** [review]
@MisterGC  should probably still take a look ;)

**Review by MisterGC — APPROVED** [review]
This PR shall pass! 🧙‍♂️

**Comment by johannes-wolf** [comment]
Canan.io PR: https://github.com/conan-io/conan-center-index/pull/23858

**Pull request merged**
